# Generated by Django 3.1.6 on 2021-05-03 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sooq', '0002_auto_20210504_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('discription', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='discripe_prodect',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='post_create',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='prodect_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='type_of_prodect',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400)),
                ('massage_date', models.DateTimeField(auto_now_add=True)),
                ('Chat_Posts_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_posts', to='sooq.posts')),
            ],
        ),
    ]
