# Generated by Django 3.1.6 on 2021-05-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sooq', '0003_auto_20210504_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='discripe_prodect',
            new_name='discripe_prod1ect',
        ),
        migrations.AddField(
            model_name='posts',
            name='prd_post_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='sooq.prodects'),
            preserve_default=False,
        ),
    ]
