# Generated by Django 3.1.6 on 2021-05-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sooq', '0005_chat_who_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=400),
        ),
    ]
