# Generated by Django 3.2.3 on 2021-05-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sooq', '0007_auto_20210520_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='discripe_prod1ect',
            new_name='discripe_prodect',
        ),
    ]
