# Generated by Django 3.2.3 on 2021-06-30 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sooq', '0008_rename_discripe_prod1ect_posts_discripe_prodect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='prd_post_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='sooq.prodects'),
        ),
    ]
